name: Deploy to Chromatic

on:
  push:
    paths:
      - packages/flitter-chart/**/*
      - packages/story/**/*
      - .github/workflows/chromatic.yml
    branches:
      - dev

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.1

      - name: Install dependencies
        run: |
          npm ci

      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/story
          buildScriptName: build-storybook
          autoAcceptChanges: true
